### ISSUE TITLE
call-service not working. key missing: targets

### ISSUE THREAD

**Issue by poudenes** [nilsreiter/home-assistant-scenes#1]
Hi All,

Add all scene like below. But it's not working. In develop tool the call-service is working correct. What can I do to solve this?

```
type: custom:paper-buttons-row
base_config:
  styles:
    icon:
      height: 90px;
      width: 90px;
buttons:
  - image: /assets/scene_presets/Adrift.jpeg
    tap_action:
      action: call-service
      service: scene_presets.start_dynamic_scene
      target: {}
      data:
        preset_id: Adrift
        targets:
          entity_id:
            - light.dressoir_1
            - light.dressoir_2
            - light.dressoir_3
            - light.livingroom_1
            - light.livingroom_2
            - light.livingroom_3
            - light.livingroom_4
            - light.balcony_1
            - light.balcony_2
        brightness: 255
        transition: 4
        interval: 4
  - image: /assets/scene_presets/Amber bloom.jpeg
    tap_action:
      action: call-service
      service: scene_presets.start_dynamic_scene
      data:
        targets:
          entity_id:
            - light.dressoir_1
            - light.dressoir_2
            - light.dressoir_3
            - light.livingroom_1
            - light.livingroom_2
            - light.livingroom_3
            - light.livingroom_4
            - light.balcony_1
            - light.balcony_2
        preset_id: Amber bloom
        brightness: 255
        transition: 3
        interval: 4
```
