### ISSUE TITLE
Calling from Automation

### ISSUE THREAD

**Issue by dmfrey** [nilsreiter/home-assistant-scenes#16]
I'm attempting to call this script from an automation but it's failing when I try to pass in the other parameters. See the `data:1 block below. The same configuration works fine when I call it from a dashboard card. Is there something I'm missing or is it not possible to use it in this manner?

This automation reads the start of a Flyers game when activated from my Google Calendar. It then attempts to reset the lights after the game is finished.

I get the following error in the Traces for this automation:
`Error: extra keys not allowed @ data['scene']`

```yaml
automation:

  - id: '738a8a9c-9792-4b41-819b-ea4cca648a8b'
    alias: "Game Time | Philadelphia Flyers"
    description: "Game Time: The Philadelphia Flyers are on"
    mode: single
    triggers:
      - trigger: state
        entity_id:
          - calendar.philadelphia_flyers
        to: "on"
        id: game_started
      - trigger: state
        entity_id:
          - calendar.philadelphia_flyers
        to: "off"
        id: game_ended
    conditions: []
    actions:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - game_started
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id:
                    - script.driveway_custom_light_scene
                    - script.firepit_custom_light_scene
                    - script.front_porch_custom_light_scene
                    - script.front_yard_custom_light_scene
                    - script.patio_custom_light_scene
                data:
                  scene: "Special: My scene"
                  repeat_delay:
                    hours: 0
                    minutes: 0
                    seconds: 45
                  onlyonlights: false
                  use_scene_brightness: false
                  brightness: 100
                  my_scene:
                    c:
                      - - 0.599
                        - 0.362
                      - - 0.313
                        - 0.329
                    b: 0.6
          - conditions:
              - condition: trigger
                id:
                  - game_ended
            sequence: 
              - service: input_boolean.turn_on
                target:
                  entity_id:
                    - input_boolean.light_reset
```

**Comment by nilsreiter** [comment]
You need to wrap the parameters to the script into an additional `variables` dict:

```
...
data:
  variables:        
                  scene: "Special: My scene"
                  repeat_delay:
                    hours: 0
                    minutes: 0
                    seconds: 45
                  onlyonlights: false
                  use_scene_brightness: false
                  brightness: 100
                  my_scene:
                    c:
                      - - 0.599
                        - 0.362
                      - - 0.313
                        - 0.329
                    b: 0.6
```

Don't ask me why :)
