### ISSUE TITLE
Error: offset should be format 'HH:MM', 'HH:MM:SS' or 'HH:MM:SS.F'

### ISSUE THREAD

**Issue by dtsn** [nilsreiter/home-assistant-scenes#3]
I've just added the blueprint and assigned a label to the blueprint; however, it's not working. 

When I try to run the script via the script interface I get the following error in the Trace:

`Error: offset should be format 'HH:MM', 'HH:MM:SS' or 'HH:MM:SS.F'`

If I try and run the script from the Developer Tools I get the following error:

`Error: In 'template' condition: UndefinedError: 'str object' has no attribute 'hours'`

Script YAML
```
alias: Backgarden Display
use_blueprint:
  path: nilsreiter/ha-scenes.yaml
  input:
    target:
      label_id: garden_display
icon: mdi:track-light
```

OS Details:
```
Core 2024.5.3
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1
```

**Comment by nilsreiter** [comment]
Yes, I noticed that too. The easiest fix is to call the script not with 'HH:MM:SS' or so, but with a YAML object:

E.g.:
```
data:
  scene: Savanna sunset
  repeat_delay:
    hours: 0
    minutes: 5
    seconds: 0
```

**Comment by dtsn** [comment]
> Yes, I noticed that too. The easiest fix is to call the script not with 'HH:MM:SS' or so, but with a YAML object:
> 
> E.g.:
> 
> ```
> data:
>   scene: Savanna sunset
>   repeat_delay:
>     hours: 0
>     minutes: 5
>     seconds: 0
> ```
> 
> This is more related to how you call the script than any of its internals (if I remember correctly).

This does remove the error; however, my lights still aren't changing:

```
alias: Garden Display
description: ""
trigger:
  - platform: sun
    event: sunset
    offset: "-2"
condition: []
action:
  - service: light.turn_on
    metadata: {}
    data: {}
    target:
      label_id: garden_display
  - service: script.backgarden_display
    data:
      scene: Osaka
      onlyonlights: false
      brightness: 100
      transition: 5
      repeat_delay:
        hours: 0
        minutes: 1
        seconds: 0
mode: single
```
Any ideas? Looking at the trace for the script it looks like it just skips all the steps which apply the colour.

<img width="931" alt="Screenshot 2024-05-15 at 13 54 15" src="https://github.com/nilsreiter/home-assistant-scenes/assets/354263/08efff42-6ded-42b1-ade8-25010d4cc183">
